### ISSUE TITLE
Have customized it for a test case level but I am unable to update the test results of multiple test cases in one report. Could you help me on this?

### ISSUE THREAD

**Issue by Srivathsmg** [Dexter-Clone/ExtentReport-SoapUI#1]
//Importing all necessary packages

import com.eviware.soapui.model.testsuite.*;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.testng.Assert;
import org.testng.ITestResult;
import org.testng.annotations.*;
import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.markuputils.ExtentColor;
import com.aventstack.extentreports.markuputils.MarkupHelper;
import com.aventstack.extentreports.reporter.ExtentHtmlReporter;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import com.aventstack.extentreports.reporter.configuration.Theme;
import com.aventstack.extentreports.AnalysisStrategy;
import java.text.*;

//Get current timestamp
SimpleDateFormat sdf = new SimpleDateFormat('yyyy-MM-dd');
def currentDateString = sdf.format(new Date())

//Creating necessary objects of Extent Reported
ExtentHtmlReporter htmlReporter;
ExtentReports extent;
ExtentTest logger;
ExtentSparkReporter spark;

/*
Defining output folder.
Kindly note context.expand('${projectDir}') will give the current Project output file directory as output.
*/

def outputFolder = context.expand('${projectDir}')+File.separator+'Reports_'+currentDateString
spark = new ExtentSparkReporter(outputFolder);
htmlReporter = new ExtentHtmlReporter(outputFolder+File.separator+"Report_"+currentDateString +".html");
extent = new ExtentReports();
extent.attachReporter(htmlReporter);
extent.attachReporter(spark);
extent.setAnalysisStrategy(AnalysisStrategy.SUITE)
projectName = testRunner.testCase.testSuite.project.getName();
//ExtentReports extent = new ExtentReports(file-path, false);

//Looping through all the test suites. Kindly note the test suites that are disables will not be considered.
testRunner.testCase.testSuite.each{
 testSuite ->
 if(!testSuite.isDisabled()){
 testsuite_logger = extent.createTest(testSuite.getName());
//Looping throught all test enabled test cases for all test suites
 testSuite.testCaseList.each{
  testCase->
strTestCaseName = testRunner.testCase.getName()
  if(testCase.getName() == strTestCaseName){
    testcase_logger = testsuite_logger.createNode(testCase.getName());
    testCase.testStepList.each{
//Looping through all test steps that are assertable
     testStep ->
      if( testStep instanceof Assertable && (!testStep.isDisabled())){
       assertionStatus = []
       testStep.getAssertionList().each{
        assertion ->
         assertionStatus.add(assertion.getStatus().toString()+" - "+assertion.getLabel())
      }
   logger = testcase_logger.createNode(testStep.getName());
   assertionStatus.each{
    if(it.startsWith("VALID -")){
     logger.log(Status.PASS, MarkupHelper.createLabel(it, ExtentColor.GREEN));
    } else if(it.startsWith("FAILED -")){
     logger.log(Status.FAIL, MarkupHelper.createLabel(it, ExtentColor.RED));
    } else {
     logger.log(Status.INFO, MarkupHelper.createLabel(it, ExtentColor.BLUE));
    }
   }
   testcase_logger.assignCategory(testSuite.name + ' - '+testCase.getName())
      }
      }
   } 
  } 
 }
}
//Generating Output
extent.flush();

**Comment by Dexter-Clone** [comment]
Hi Srivasthsmg, This utility was created to work for project level execution only.
